# Generated by Django 5.1.3 on 2025-05-02 19:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Пополнение, Списание', max_length=100, unique=True, verbose_name='Тип операции')),
            ],
            options={
                'verbose_name': 'Тип операции',
                'verbose_name_plural': 'Типы операций',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Бизнес, Личное, Налог', max_length=100, unique=True, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категория')),
                ('operation_type', models.ForeignKey(help_text='Категория принадлежит определённому типу операции', on_delete=django.db.models.deletion.CASCADE, to='CashFlow.operationtype', verbose_name='Тип операции')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'unique_together': {('name', 'operation_type')},
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Подкатегория')),
                ('category', models.ForeignKey(help_text='Подкатегория принадлежит определённой категории', on_delete=django.db.models.deletion.CASCADE, to='CashFlow.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, help_text='Дата создания записи. По умолчанию — сегодня.', verbose_name='Дата записи')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Укажите сумму в рублях, например 1000.00', max_digits=12, verbose_name='Сумма')),
                ('comment', models.TextField(blank=True, help_text='Необязательный комментарий к записи', null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CashFlow.category', verbose_name='Категория')),
                ('operation_type', models.ForeignKey(help_text='Пополнение или Списание', on_delete=django.db.models.deletion.PROTECT, to='CashFlow.operationtype', verbose_name='Тип операции')),
                ('status', models.ForeignKey(help_text='Выберите статус: Бизнес, Личное и т.д.', on_delete=django.db.models.deletion.PROTECT, to='CashFlow.status', verbose_name='Статус')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CashFlow.subcategory', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Денежная операция',
                'verbose_name_plural': 'Денежные операции',
                'ordering': ['-date'],
            },
        ),
    ]
